---
- name: Get bridge repo
  git:
    repo: "{{ bridge_repo }}"
    dest: "{{ bridge_path }}"
    force: no
    update: no
    version: "master"

- name: Checkout proper branch
  shell: |
    if [ ! "$CIRCLE_PR_NUMBER" = "" ]
    then # If this is a forked PR, the branch needs to be fetched in a special way
      git fetch --force --depth 1 origin -- "{{ bridge_repo_branch }}/head:remotes/origin/{{ bridge_repo_branch }}"
      git branch {{ bridge_repo_branch }} origin/{{ bridge_repo_branch }} 
      echo 'Branch from forked PR fetched'
    fi

    git checkout {{ bridge_repo_branch }}
  args:
    chdir: "{{ bridge_path }}"

- name: Initialize submodules
  shell: git submodule update --init --depth 1
  args:
    chdir: "{{ bridge_path }}"
